#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamTrack.Droid.Resource", IsApplication=true)]

namespace XamTrack.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class AddTask
		{
			
			// aapt resource value: 0x7f050007
			public const int Add = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int BottomLayout = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Cancel = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int Header = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int NameInput = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int NameItem = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int TaskInfo = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int TopLayout = 2131034112;
			
			static AddTask()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AddTask()
			{
			}
		}
		
		public partial class TrackingOverview
		{
			
			// aapt resource value: 0x7f060006
			public const int AddTask = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int BottomLayout = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int CurrentTaskName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CurrentTaskTime = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int TaskList = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int TopLayout = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int TotalTaskTime = 2131099651;
			
			static TrackingOverview()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private TrackingOverview()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddTask = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TrackingOverview = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
