// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamTrack.iOS
{
	public partial class AddReportViewController : UIViewController
	{
		public AddReportViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			CreateBtn.TouchUpInside += CreateBtn_TouchUpInside;
			NameInput.AllEvents += NameInput_ValueChanged;

			RefreshUI();
		}

		void CreateBtn_TouchUpInside(object sender, EventArgs e)
		{
			string reportName = NameInput.Text.Trim();
			if (string.IsNullOrEmpty(reportName))
				return;
			
			ReportManager.Instance.AddReport(reportName);
		}

		void NameInput_ValueChanged(object sender, EventArgs e)
		{
			RefreshUI();
		}

		private void RefreshUI()
		{
			InvokeOnMainThread(() =>
			{
				CreateBtn.Enabled = !string.IsNullOrEmpty(NameInput.Text.Trim());	
			});
		}
	}
}
